language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy"
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls==0.4.2
script:
    - cd tests/
    - py.test --cov cpe --doctest-modules .
    - cd ../docs/
    - sphinx-build -W -b html -d $(mktemp)/doctrees . $(mktemp)/html
after_success:
    - coveralls
